### ISSUE TITLE
ArgoCD prod roll out not working

### ISSUE THREAD

**Issue by YogeshBhatiaAWS** [shapirov103/appmod-blueprints#24]
Upon creating Prod folder, argocd is getting setup but all the other apps are failing, need to troubleshoot with Mikhail. Also ELB is not getting created as no subnet found, need to ensure the reason. Probably there is no public subnet configured for the PROD EKS cluster

**Comment by shapirov103** [comment]
it is fixed in https://github.com/shapirov103/appmod-blueprints/commit/4441a2886e1b23c91dea0c93c0f3278399c22edc
also in the workshop.
