### ISSUE TITLE
DEV Cluster ArgoCD ELB getting deletd

### ISSUE THREAD

**Issue by YogeshBhatiaAWS** [shapirov103/appmod-blueprints#26]
Every few mins ArgoCD ELB getting deleted

**Comment by shapirov103** [comment]
haven't we decided to switch to port forward and URL preview feature in C9? We have bigger issues to address at this point. 

To answer your question on how enable external access to argoCD UX, please follow this doc for ALB and Argo: https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#aws-application-load-balancers-albs-and-classic-elb-http-mode
